# Generated by Django 6.0.6 on 2026-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
