# Generated by Django 6.0.6 on 2026-07-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chai_certificate_chai_review_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chai_certificate',
            old_name='certicate_number',
            new_name='certificate_number',
        ),
    ]
